# VOICE SPECIFICATIONS (Constants for reuse)
FEMALE_VOICE_SPEC = (
    "Nigerian female (mid‑30s) voice spec: record/normalize to **‑16 LUFS integrated** "
    "(dialogue target), with **true‑peak ≤‑2.0 dBTP** and average spoken level around "
    "**‑18 dBFS RMS** (peaks typically **‑6 to ‑3 dBFS** pre‑master); **pace 150 wpm** "
    "(±10 wpm), conversational but efficient; **fundamental pitch range 165–240 Hz** "
    "with **modal center ~195 Hz** and controlled variation (**±25–35 Hz** within phrases) "
    "for natural emphasis; **tone quality** warm‑neutral and polished with slight "
    "high‑frequency “presence” (not airy), low sibilance, low rasp; **articulation** "
    "crisp consonants, fully voiced vowels, minimal elision, medium plosive energy; "
    "**intonation** Nigerian English cadence: steady, confident contours with gentle "
    "downstep on declaratives and modest rise on interrogatives, emphasis via slight "
    "pitch lift + micro‑pause rather than volume spikes; **delivery style** "
    "professional, friendly, assured (corporate explainer), medium dynamics (**~6–8 dB** "
    "range), no exaggerated theatrics; **pauses** 150–250 ms between clauses, 300–450 ms "
    "between sentences, 600–900 ms at section breaks; **resonance** forward placement "
    "with balanced chest/head mix (avoid nasal focus), clear formant definition; "
    "for consistency in recording/AI: **48 kHz/24‑bit**, cardioid mic, **15–20 cm** "
    "mouth‑to‑mic with pop filter, room RT60 **≤0.3 s**, noise floor **≤‑60 dBFS**, "
    "light compression **2:1** (2–4 dB GR), HPF **80 Hz**, gentle presence boost "
    "**+2 dB @ 3.5–4.5 kHz**, de‑ess centered **6–8 kHz** (2–5 dB), and maintain "
    "identical mouth posture/energy across takes."
)

MALE_VOICE_SPEC = (
    "Nigerian male (mid‑30s) voice spec: master dialogue to **‑16 LUFS integrated** "
    "with **true‑peak ≤‑2.0 dBTP**; track at ~**‑18 dBFS RMS** average speech with "
    "natural peaks **‑7 to ‑3 dBFS** pre‑limiter; **pace 145 wpm** (±10), confident "
    "and measured; **fundamental pitch range 95–155 Hz** with **modal center ~120 Hz**, "
    "phrase movement typically **±15–25 Hz** (wider only on key emphasis); **tone quality** "
    "warm, slightly dark and “smooth” with moderate presence (not breathy, minimal rasp), "
    "controlled sibilance and plosives; **articulation** clear Nigerian English consonants, "
    "firm but not over‑enunciated, moderate vowel length, light consonant releases on "
    "line ends; **intonation** steady, authoritative contours with gentle downstep on "
    "statements, restrained rises on questions, emphasis via slight pitch lift + stress "
    "on content words rather than volume jumps; **delivery style** professional "
    "corporate/tech narrator—friendly, assured, low‑drama, medium dynamic range "
    "(**~6–9 dB**) and consistent energy; **pauses** 140–220 ms between clauses, "
    "280–420 ms between sentences, 650–950 ms between sections; **resonance** "
    "forward and chest‑supported with balanced formants (avoid nasal focus), stable "
    "proximity effect; for repeatability in recording/AI: **48 kHz/24‑bit**, cardioid "
    "mic, **15–18 cm** mouth distance with pop filter, room RT60 **≤0.3 s**, "
    "noise floor **≤‑60 dBFS**, light compression **2:1** (2–5 dB GR), **HPF 70–80 Hz**, "
    "gentle presence **+1.5 to +2.5 dB @ 3–4.5 kHz**, de‑ess **6–8 kHz** (2–5 dB), "
    "and maintain identical mic position, speaking posture, and hydration across sessions."
)
